<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="3" hostname="DESKTOP-NCHRHGP" failures="1" tests="1" name="ScenariosTest(failed)" time="0.053" errors="0" timestamp="2021-05-25T10:46:07 IST">
  <testcase classname="testNGPrograms.Q5_FailedTest_Program" name="test2" time="0.01">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:87)
at org.junit.Assert.assertTrue(Assert.java:42)
at org.junit.Assert.assertTrue(Assert.java:53)
at testNGPrograms.Q5_FailedTest_Program.test2(Q5_FailedTest_Program.java:17)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- test2 -->
  <testcase classname="testNGPrograms.Q5_FailedTest_Program" name="test3" time="0.0">
    <ignored/>
  </testcase> <!-- test3 -->
  <testcase classname="testNGPrograms.Q5_FailedTest_Program" name="test4" time="0.0">
    <ignored/>
  </testcase> <!-- test4 -->
  <testcase classname="testNGPrograms.Q5_FailedTest_Program" name="test1" time="0.0">
    <ignored/>
  </testcase> <!-- test1 -->
</testsuite> <!-- ScenariosTest(failed) -->
